name: Deploy Python QuickNote App to Azure Web App

on:
  push:
    branches:
      - main # Or your deployment branch
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Set up Python version'
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 'Install application dependencies (for deployment artifact)'
      run: |
        python -m venv antenv
        source antenv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        # Deactivate not strictly necessary here as the venv is for the zip
        # but good practice if you were doing more in this shell.
        # deactivate

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Zip artifact for deployment'
      run: zip -r release.zip . -x ".git/*" ".github/*" "antenv/*" "*.pyc" "__pycache__/*" ".DS_Store"

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
        package: release.zip

    # --- FIX APPLIED HERE ---
    - name: Install dependencies for documentation script
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # This will install to the Python used by setup-python

    - name: Generate and Publish Documentation
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
        CONFLUENCE_EMAIL: ${{ secrets.CONFLUENCE_EMAIL }}
        CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
        CONFLUENCE_SPACE_KEY: ${{ secrets.CONFLUENCE_SPACE_KEY }}
        ROOT_DOC_TITLE: "${{ github.repository }} - Project Docs"
        CODE_ROOT_PATH: "."
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: python scripts/doc_generator.py

    - name: 'Logout from Azure'
      if: always()
      run: |
        az logout
        az account clear